### ISSUE TITLE
API calls for menu items

### ISSUE THREAD

**Issue by Jit-everywhere** [Jit-everywhere/JIT#25]
1)post for saving menu items
2)patch operations
3)sorting based on A-Z food items with price and stock

**Comment by KaviyarasanK3** [comment]
Api calls for post, put, getAll, getByID are checked for food table. post, getAll, getByID checked for category, address, restaurant, orderItems tables. Needed to check the rest of the API calls to close this issue.

**Comment by KaviyarasanK3** [comment]
All Crud operations modified and verified on Address, Restaurant, food, category and menuItem entities.
