### ISSUE TITLE
Create Tunneling for SQL DB

### ISSUE THREAD

**Issue by Jit-everywhere** [Jit-everywhere/JIT#3]
In order to provide common access of JIT_DB 
create SSH access and same root name with different password

**Comment by KaviyarasanK3** [comment]
Please follow the steps below to connect to the SQL DB,
![Image](https://github.com/user-attachments/assets/b382221b-2c48-40f8-bcb0-f8eaa22f4be1)
CA certificate will be shared on request, Thanks!
